#!/usr/bin/env node
/**
 * configure.js
 *
 * 1. Discovers Node.js include directory
 * 2. Resolves the node-addon-api header path (installs it via npm if missing)
 * 3. Writes build/node_vars.cmake consumed by CMakeLists.txt
 *
 * Usage:  node configure.js
 */

'use strict';

const fs   = require('fs');
const path = require('path');
const cp   = require('child_process');

// ── 1. Locate node headers ───────────────────────────────────────────────────
const nodeExe    = process.execPath;
const nodePrefix = process.config?.variables?.node_prefix
                ?? path.dirname(path.dirname(nodeExe));

const candidates = [
  path.join(nodePrefix, 'include', 'node'),
  path.join(path.dirname(path.dirname(nodeExe)), 'include', 'node'),
  '/usr/include/node',
  '/usr/local/include/node',
  // headers installed by node-gyp
  path.join(
    process.env.HOME ?? process.env.USERPROFILE ?? '',
    '.cache', 'node-gyp', process.versions.node, 'include', 'node'
  ),
];

let nodeInclude;
for (const c of candidates) {
  if (fs.existsSync(path.join(c, 'node_api.h'))) { nodeInclude = c; break; }
}

if (!nodeInclude) {
  console.error('[configure.js] ERROR: node_api.h not found.');
  console.error('  Try running:  node-gyp install');
  process.exit(1);
}

// ── 2. Locate node-addon-api headers ────────────────────────────────────────
//   node-addon-api exposes its include path via require('node-addon-api')
let napiInclude;
try {
  // This returns the path to the folder containing napi.h
  napiInclude = require('node-addon-api').include_dir;
  // Verify the header actually exists there
  if (!fs.existsSync(path.join(napiInclude, 'napi.h'))) throw new Error('napi.h not found');
} catch (_) {
  console.log('[configure.js] node-addon-api not found — installing locally...');
  cp.execSync('npm install node-addon-api', { stdio: 'inherit' });
  try {
    napiInclude = require('node-addon-api').include_dir;
  } catch (e) {
    console.error('[configure.js] ERROR: Failed to resolve node-addon-api:', e.message);
    process.exit(1);
  }
}

// ── 3. Write cmake vars ───────────────────────────────────────────────────────
fs.mkdirSync('build', { recursive: true });

const cmake = `\
# Auto-generated by configure.js — do not edit
set(NODE_EXECUTABLE      "${nodeExe.replace(/\\/g, '/')}")
set(NODE_VERSION         "${process.version}")
set(NODE_INCLUDE_DIR     "${nodeInclude.replace(/\\/g, '/')}")
set(NODE_MODULE_VERSION  "${process.versions.modules}")
set(NAPI_INCLUDE_DIR     "${napiInclude.replace(/\\/g, '/')}")
`;

fs.writeFileSync(path.join('build', 'node_vars.cmake'), cmake);

console.log('[configure.js] Node.js        :', process.version);
console.log('[configure.js] Node headers   :', nodeInclude);
console.log('[configure.js] node-addon-api :', napiInclude);
console.log('[configure.js] ABI            :', process.versions.modules);
console.log('[configure.js] Written        : build/node_vars.cmake');
console.log('[configure.js] Done. Run: npm run cmake:build');
